/* PROBLEM: 1907. Count Salary Categories
DIFFICULTY: Medium
TOPIC: Advanced Select and Joins & Reporting Skeleton Patterns

LOGIC:
The objective is to report the number of bank accounts in three specific 
salary categories. A key requirement is that all three categories must 
appear in the result, even if they have zero accounts. We achieve this by:
1. Creating a "Skeleton" CTE ('categories') that explicitly defines the 
   required output rows.
2. Categorizing the actual data in a second CTE ('incomes') using a CASE statement.
3. Using a LEFT JOIN to ensure categories with no matching data return 0 
   instead of being omitted.

ARCHITECTURAL NOTE: 
1. The Skeleton Pattern: In production reporting (like financial audits), 
   missing rows can be interpreted as "data errors" rather than "zero values." 
   By using a 'UNION ALL' skeleton as the base of our join, we guarantee 
   the structural integrity of the final report.
2. Count vs. Count(*): We use 'COUNT(b.income_cat)'. This is critical because 
   COUNT(column) ignores NULL values generated by the LEFT JOIN, allowing us 
   to correctly report 0 for empty categories. Using COUNT(*) would 
   incorrectly return 1 for empty categories.
3. Range Logic: The 'BETWEEN' operator and strict inequality ('<') are used 
   to create mutually exclusive and collectively exhaustive (MECE) ranges, 
   ensuring every account is counted exactly once.
*/

WITH categories AS (
    SELECT 'Low Salary' AS cat
    UNION ALL
    SELECT 'Average Salary'
    UNION ALL
    SELECT 'High Salary'
), incomes AS (
    SELECT
        CASE
            WHEN income < 20000 THEN 'Low Salary'
            WHEN income BETWEEN 20000 AND 50000 THEN 'Average Salary'
            ELSE 'High Salary'
        END AS income_cat
    FROM accounts
)
SELECT
    a.cat AS category,
    COUNT(b.income_cat) AS accounts_count
FROM categories AS a
LEFT JOIN incomes AS b
  ON a.cat = b.income_cat
GROUP BY a.cat;
